name: blog
toolchainRegion: us-west-2
forceDependencyRedeploy: True
groups:
  - name: optionals
    path: manifests/optional-modules.yaml
  - name: core
    path: manifests/core-modules.yaml
  - name: pre-processing
    path: manifests/pre-processing-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId: 123456789012 # Adjust to your AWS Account id
    default: true
    regionMappings:
      - region: us-west-2
        default: true

