name: networking
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.11.0&depth=1
parameters:
  - name: internet-accessible
    value: true
---
name: ecr
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/ecr?ref=release/1.11.0&depth=1
parameters:
  - name: repository-name
    value: image-extraction-using-mps3
  - name: image-tag-mutability
    value: MUTABLE
  - name: image-scan-on-push
    value: True
  - name: removal-policy
    value: DESTROY
---
name: buckets
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/buckets?ref=release/1.11.0&depth=1
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-type
    value: DESTROY
